# libs Makefile

LIBSDIR=../

all:
	$(MAKE) -C shtns-2.6.6-r535 LIBSDIR="$(LIBSDIR)"
#	$(MAKE) -C fftw-3.3.4 -f Makefile_conf LIBSDIR="$(LIBSDIR)"

clean:
	$(MAKE) -C shtns-2.6.6-r535 clean
#	$(MAKE) -C fftw-3.3.4 -f Makefile_conf clean
	rm *.a

