# post Makefile

include ../macros.make

all:
	$(MAKE) -C gribio
	$(MAKE) -C vlint
	$(MAKE) -C iplib
	$(MAKE) -C pop
#	$(MAKE) -C plot_icos

clean:
	$(MAKE) -C gribio    clean
	$(MAKE) -C vlint     clean
	$(MAKE) -C iplib     clean
	$(MAKE) -C pop       clean
#	$(MAKE) -C plot_icos clean
